### ISSUE TITLE
cic: no one looking to switch account finds Detach — the verbs are named for the bouncer, not the intent

### ISSUE THREAD

**Issue by vjt** [vjt/grappa-irc#1705]
Reported in channel by a self-hoster, twice in twenty minutes:

> non riesco a fare logout con un utente e rientro con un altro utente

> si non avevo capito che il bottone fosse detach

## What the app offers today

`cicchetto/src/lib/lifecycle.ts:11-27` retired **logout** as a user-facing verb (#126): the
two entries are **Detach** (web down, bouncer up — `DELETE /auth/logout`, bearer revoked) and
**Quit IRC** (web down *and* upstream down — `quitAll` parks every network, then the same
detach). Both clear the token and land on `/login`, so switching accounts already works.

There is no third verb: `grep -rn "Switch identity\|switchIdentity"` over the tree returns
**nothing** — the affordance #282's title alludes to does not exist in the code.

## The gap

The verbs are named after **what happens to the bouncer**, which is the right axis for the
consequence and the wrong one for the intent "I want to be someone else here". A user looking
to change account scans the menu for a word that is deliberately absent, finds two entries
that both talk about IRC connections, and concludes the thing cannot be done.

Reporter is not a casual visitor: he self-hosts the app.

## Not a copy bug

The modal bodies are accurate and subject-routed (`quitBody()`, #986) — the problem is
upstream of them, at the point where the entry is *read in the menu*, before any modal opens.

## Not queued — needs a ruling on the shape

Candidates, no decision taken here:

1. Leave the verbs, add the missing word where it is looked for (e.g. a `Detach` subtitle that
   says "log out of cicchetto / switch account").
2. A real `Switch account` entry that runs `detach()` and lands on `/login` — no new teardown,
   just the intent named.
3. Nothing, and treat it as a docs line.

Related: #43 (the original split into two buttons), #126 (the vocabulary), #282, #986.

**Comment by vjt** [comment]
Same reporter, on the icon rather than the word:

> la spina elettrica staccata forse non e' l'emoji migliore mmm

Measured in `cicchetto/src/RailActions.tsx:731`: **detach** renders `U+1F50C` 🔌 (electric
plug), **quit** at `:753` renders `U+1F6AA` 🚪 (door). The pairing is backwards against the
verbs' own semantics — the plug says *the connection is being pulled*, which is precisely
what detach does **not** do (the bouncer keeps running, that is the whole point), while the
door is the milder image and sits on the entry that actually takes the upstream session down.

Belongs to this issue: the label and the glyph are the same read, made before any modal opens.

**Comment by vjt** [comment]
Ruling in channel, recorded here so the queue does not pick this up: vjt handed this issue to
the reporter — "sentiti libero di prenderti in carico 1705". It stays **out of `status:queued`**
and off the worker pipeline; the icon swap (🔌 / 🚪, `RailActions.tsx:731` and `:753`) comes as
an external PR.

The wider half of the issue — the missing word for "switch account" — is **not** ruled on yet.

**Comment by vjt** [comment]
## Ruling: shape 2 — a `Switch account` entry

vjt, #grappa 2026-08-23 21:15: **"switch account … è molto meglio di detach"**.

So candidate **2** is taken, and the wording goes further than "add an entry": the intent
name is held to be *better* than the bouncer name at the point where the menu is read.
Candidates 1 and 3 are off the table.

The icon half of this issue is already closed by #1706 (`124c7724`, merged 21:05): the
swapped `RailActions.tsx:731`/`:753` emoji are right way round now. What remains is only
this.

### `logout` is not the word (asked in the same thread)

`cicchetto/src/lib/lifecycle.ts:11-27` retired it deliberately in #126. The vocabulary is
routed off the (web client × upstream IRC) matrix:

```
web UP   + upstream UP   = normal
web UP   + upstream DOWN = per-network park/reconnect (home page)
web DOWN + upstream UP   = detach
web DOWN + upstream DOWN = quit
```

"logout" names no cell of it — it does not say whether the bouncer stays up — and for an
ephemeral visitor the thing that used to be called logout **is** what is now `quit`.
`Switch account` is safe in a way `logout` is not: it names the *intent* and claims nothing
about the connection, so it does not re-open the ambiguity #126 closed.

### One constraint the label must not step on — measured, not assumed

`detach()` is `logout()` (`lifecycle.ts:34-36`), and `logout()` calls `DELETE /auth/logout`
(`auth.ts:297-311`). For a **persistent identity** that is a pure web-session revoke — row
and scrollback survive, bouncer stays up — and "switch account" is an honest label.

For an **ephemeral (anon) visitor** it is not: the anon branch of `DELETE /auth/logout`
**stops every attached session and purges the row server-side** (`lifecycle.ts:51-53`,
`:69-71`). Offering that visitor an entry that says "Switch account" would promise a
reversible change and deliver a destructive one.

⇒ the entry must be gated on the existing `isPersistentIdentity(getSubject())` predicate
(`lifecycle.ts:64`), the same one `quit()` already routes on — not on subject class, which
#477 collapsed for exactly this reason. For an ephemeral visitor the truthful entry is the
one that already exists.

### Scope

No new teardown path: the entry runs `detach()` and the existing reactive `RequireAuth`
bounce (`main.tsx:356`) lands on `/login`. This is naming + gating, not lifecycle work.

Assigned to @pminervini by vjt. Not queued to the worker fleet.

**Comment by vjt** [comment]
## Shipped — and two corrections to the comment above

`bc9c6c9d` on `main`.

**Correction 1 — the ruling is narrower than "add an entry".** vjt refined it in the same
breath: *"cambiamo solo detach in switch account e abbiam fatti"*. So this is a **rename of
the existing entry**, not a third one. Nothing was added to the rail. His reason for
rejecting `logout`, which is worth keeping next to #126's: *"logout si confonde tra logout
cic e logout irc, e c'è già quit"*.

**Correction 2 — the constraint I raised above does not apply, and I should have checked
before raising it.** I wrote that the entry would need gating on `isPersistentIdentity`
because `DELETE /auth/logout`'s anon branch purges the row. True about the branch, wrong
about the risk: `canDetach()` (`lifecycle.ts:117`) **is** `isPersistentIdentity(getSubject())`,
so an ephemeral visitor is never shown this entry at all — the gate #986 already put there
is exactly the one I was asking for. No gating work exists in this issue.

### What changed

- `RailActions.tsx` — the label and `aria-label` read `switch account`.
- `lifecycle.ts` — `confirmDetach`'s modal `title` and `confirmLabel` follow it.
- `RailActions.test.tsx` — the label assertion follows.

`detach()`, `rail-action-detach`, `detach-btn` and the teardown are untouched, so every e2e
spec that drives this by testid is unaffected. `DETACH_BODY` is unchanged: it still says the
bouncer keeps running and the scrollback keeps filling, which is the half no label conveys.

### What I verified, and what I did not

`npx tsc --noEmit` clean (exit 0). The unit tests I **could not run here**: this host's jsdom
is broken (`webidl.util.markAsUncloneable is not a function`, node/undici) and `npm run check`
shells out to `bun`, which is not installed. So `RailActions.test.tsx` and `lifecycle.test.ts`
are unrun locally — CI is the measure, not me.

The icon half of this issue landed in #1706 (`124c7724`, @pminervini). With both halves in,
this issue is done unless the rename reads wrong on device.

**Comment by vjt** [comment]
Both legs are on `main`.

- **icon half** — PR #1706, merged 2026-08-23T19:05:21Z
- **discoverability half** — `bc9c6c9d`, merged 2026-08-23T19:19:06Z: the entry now reads "switch account" (per the ruling *"cambiamo solo detach in switch account"* — only the words the operator sees changed; `quit` was left alone)
- **e2e follow-up** — PR #1712, merged 2026-08-23T20:19:20Z

The middle commit renamed the label without updating the two e2e specs that assert the words, which reddened `main` (`issue473-rail-actions-drawer` and `issue43-split-logout`; `Expected: "detach"` / `Received: "switch account"`). #1712 aligned both — the exact word moved, not loosened into a regex, so the specs still fail if the label drifts again.

**Correction to the first version of this comment:** it said *"main is green again at 99ea9681"*. That was wrong — I quoted PR #1712's pre-merge green as if it were main's post-merge result. At the time of writing, both `ci` and `integration` on `99ea9681` were still `in_progress`. What is measured is narrower: #1712 was green on its own head before merging, and the merge was a pure fast-forward. Whether main's own run passes is a separate observation, not yet made here.

Closing at the merge, so this names no release tag yet.
